### ISSUE TITLE
关于SDF阴影

### ISSUE THREAD

**Issue by DearIcer** [FernRender/FernNPR#3]
亮面和暗面好像写反了。
![Snipaste_2023-02-11_21-11-41](https://user-images.githubusercontent.com/56225620/218259860-36719422-b1d3-49bf-bea5-aed747507585.png)
![image](https://user-images.githubusercontent.com/56225620/218259876-b185746b-2618-4dc2-9b5b-2fac245831c7.png)
我需要把颜色反过来效果才正确
![image](https://user-images.githubusercontent.com/56225620/218259897-bb53c256-c3f5-4d84-94b7-8ccc56e572e9.png)
![image](https://user-images.githubusercontent.com/56225620/218259915-04576711-b92a-46ef-b4be-3c457e5dea2c.png)

**Comment by DeJhon-Huang** [comment]
感谢！我会检查一下。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月11日 21:13
收件人: ***@***.***>
抄送: ***@***.***>
主题: [DeJhon-Huang/FernNPR] 关于SDF阴影 (Issue #3)


亮面和暗面好像写反了。
[Snipaste_2023-02-11_21-11-41]<https://user-images.githubusercontent.com/56225620/218259860-36719422-b1d3-49bf-bea5-aed747507585.png>
[image]<https://user-images.githubusercontent.com/56225620/218259876-b185746b-2618-4dc2-9b5b-2fac245831c7.png>
我需要把颜色反过来效果才正确
[image]<https://user-images.githubusercontent.com/56225620/218259897-bb53c256-c3f5-4d84-94b7-8ccc56e572e9.png>
[image]<https://user-images.githubusercontent.com/56225620/218259915-04576711-b92a-46ef-b4be-3c457e5dea2c.png>

―

**Comment by DeJhon-Huang** [comment]
你还可以尝试勾选Direction Reversal，因为sdf face tex的方向不一定是一致的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: DearIce ***@***.***>
发送时间: Saturday, February 11, 2023 9:13:48 PM
收件人: DeJhon-Huang/FernNPR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [DeJhon-Huang/FernNPR] 关于SDF阴影 (Issue #3)


亮面和暗面好像写反了。
[Snipaste_2023-02-11_21-11-41]<https://user-images.githubusercontent.com/56225620/218259860-36719422-b1d3-49bf-bea5-aed747507585.png>
[image]<https://user-images.githubusercontent.com/56225620/218259876-b185746b-2618-4dc2-9b5b-2fac245831c7.png>
我需要把颜色反过来效果才正确
[image]<https://user-images.githubusercontent.com/56225620/218259897-bb53c256-c3f5-4d84-94b7-8ccc56e572e9.png>
[image]<https://user-images.githubusercontent.com/56225620/218259915-04576711-b92a-46ef-b4be-3c457e5dea2c.png>

―
